<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Krishna-PC" failures="2" tests="3" name="Test" time="10.317" errors="0" timestamp="2023-06-15T21:30:26 CDT">
  <testcase classname="TestCases.DemoTest" name="Logo" time="0.094"/>
  <testcase classname="TestCases.DemoTest" name="Login" time="0.924">
    <failure type="java.lang.AssertionError" message="expected [invalid msgs] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]">
      <![CDATA[java.lang.AssertionError: expected [invalid msgs] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]
at TestCases.DemoTest.Login(DemoTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="TestCases.DemoTest" name="Register" time="0.004">
    <failure type="org.testng.TestException" message="
Method DemoTest.Register()[pri:3, instance:TestCases.DemoTest@1e63d216] should have thrown an exception of type class org.testng.SkipException">
      <![CDATA[org.testng.TestException: 
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Register -->
</testsuite> <!-- Test -->
